default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost
  port: 5432
  username:
  password:

development:
  <<: *default
  database: 'admin_permissions_app_dev'

test:
  <<: *default
  database: 'admin_permissions_app_test'

production:
  <<: *default
  database: admin_permissions_app_prod
